title: "Michael Wigton"
email: "mawigton@gmail.com"
description: "Senior software engineer building interactive applications, tools, and immersive experiences."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michaelwigton.com"
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
exclude: ["node_modules"]
collections:
  projects:
    output: false

# Build settings
permalink: /:title/